### ISSUE TITLE
why there is an alpha for the heatmap

### ISSUE THREAD

**Issue by linshuxi** [gathierry/FashionAI-KeyPointsDetectionOfApparel#11]
Hello, thank you very much for the excellent work.
There is an alpha constant multiplied with the heatmap, and in the configure file the constant is 100, did you get better accuracy with the constant ? I read a few repos and there is no alpha constant, which make me a little confused.

**Comment by gathierry** [comment]
Hi, the alpha is the amplitude of the gaussian shape. As the optimization is trying to regress the gaussian, alpha is like a scale multiplied to the loss. I have impression that I tried several different alpha and 100 was the best one. But this might can be achieved by adjusting learning rate as well.
