### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by rahulbarnwal** [gathierry/FashionAI-KeyPointsDetectionOfApparel#3]
@gathierry ,  FashionAI-KeyPintsDetectionofApparel got over on 5th of july. I came across this competition last week only. Though i already signed up, i am unable to access their dataset probably because the competition is already over. Could you share the dataset with me if you still have it ?

**Comment by NuclearCaty** [comment]
Hello, @gathierry, the same question - can't get dataset from original competition site :( Please, could you share it?

**Comment by gathierry** [comment]
@rahulbarnwal @NuclearCaty Sorry but I'm afraid I don't have the right to do so.
The organizer promised to open the dataset and the submission as well after the competition. Maybe they are still working on it. I'll update this issue if I have any news about it.
