### ISSUE TITLE
Is there anyway to improve the detection speed or lower the weight file?

### ISSUE THREAD

**Issue by Sibozhu** [gathierry/FashionAI-KeyPointsDetectionOfApparel#7]
Thank you guys so much for this amazing repo, it's very inspiring to me. 

Currently, I'm writing a project doing keypoints detection on traffic cone (which is similar to cloth but objects are much simpler). With only one class and 7 named keypoints on traffic cone keypoints, my trained network is about 300MB big and the inference speed is about 9 images per second on my 8GB RAM GTX1080. That means, the architecture is too deep here and the detection speed is kinda slow. The ideal detection speed would be 300 images per second under the same hardware.

Do you have any suggestions on how to modify the architecture to achieve that? Or maybe the Cascaded Pyramid Network is just too fancy for the traffic cone task?

Thank you so much!

Best Regards,
Sibo Zhu

**Comment by gathierry** [comment]
Hi, thanks for your feedback. If I understood correctly, you need a simpler network for your "real-time" task. I'm not sure CPN is the best choice in this scenario, but if you keep using it, here's something you can have a try.
First, you can try a lighter backbone such as ResNet18, Xception or MobileNet;
Second, try to use only the smallest feature map in the cascaded part (currently feature maps of three different scales are used);
You can also reduce the layer number in the cascaded part which may help a little bit.
As far as I know, the most efficient approaches for key point detection are OpenPose and AlphaPose. You can take a look at these methods if CPN cannot achieve the goal.

**Comment by Sibozhu** [comment]
Thank you so much for the rapid reply! Will definitely try those approaches.

I hope I can talk with you more in the future, but right now I'll just close this issue.

**Comment by Sibozhu** [comment]
Thank you so much for the former advice on the network adjustment. I changed the backbone from the original ResNet152 to ResNet50 and the inference speed is roughly 1.5 times faster so I decided to go further on tuning your network.

`def GlobalNet18(config, pretrained=False):
    return GlobalNet(config, Bottleneck, [2, 2, 2, 2], torchvision.models.resnet18(pretrained=pretrained))`
For changing backbone to ResNet18, it seems like I couldn't just replace the torchvision module name from resnet152 to resnet18 like the code above, otherwise, I got an error message like this:
`RuntimeError: Given groups=1, weight of size [256, 2048, 1, 1], expected input[4, 512, 2, 2] to have 2048 channels, but got 512 channels instead` 
I can see from your code that each backbone comes with a set of customized "num_blocks". With all my respect, how is that generated or calculated, for using ResNet18 for backbone, does calculating the num_blocks number would solve the error above once for all? 

Also, for the chopping off the all the feature maps but the first one, can you give me some suggestions on which part of your code should I go to?

Thank you so much for your great work!

**Comment by gathierry** [comment]
1. I think your modification is correct. The first parameter of Conv2d is the input channel, so it should be coherent with the feature map of ResNet. I've never tested ResNet18 but it seems like its channel numbers is different from ResNet50 or ResNet152. In fact, this global net is modified based on the [official implementation of resnet](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py).
2. I think you are right about the inference speed vs input scale. I don't understand this phenomena either. Are you sure the images are exactly scaled to 96?
3. For example in RefineNet
```
def forward(self, p2, p3, p4, p5):
        p4 = self.bottleneck4(p4)
        p5 = self.bottleneck5(p5)
        return self.output(torch.cat([p4, p5], dim=1))
```
Then the forward will only pass the two smallest feature maps.
You can even try to simplify the GlobalNet by removing small-strided features.
```
        # Bottom-up
        c1 = F.relu(self.bn1(self.conv1(x)))
        c1 = F.max_pool2d(c1, kernel_size=3, stride=2, padding=1)
        c2 = self.layer1(c1)
        c3 = self.layer2(c2)
        c4 = self.layer3(c3)
        c5 = self.layer4(c4)
        # Top-down
        p5 = self.latlayer1(c5)
        p4 = self._upsample_add(p5, self.latlayer2(c4))
        p4 = self.toplayer1(p4)
        return p4, p5
```
Note that the output size is changed in this case and you might need to modify the decoder part as well.
