### ISSUE TITLE
FashionAI dataset is not available 

### ISSUE THREAD

**Issue by mitraavi** [gathierry/FashionAI-KeyPointsDetectionOfApparel#8]
@gathierry 

It was excellent to see your code and results, thank you for sharing the training code. 
However, I couldn't find FashionAI dataset from their site, seems dataset is no more available. Could you please share trained model for inference. It will be very helpful for us to test it.

Best, 
Abhishek

**Comment by cafedeflore** [comment]
@gathierry  能分享一下训练的数据集吗，非常感谢

**Comment by gathierry** [comment]
> @gathierry 能分享一下训练的数据集吗，非常感谢

find it here https://tianchi.aliyun.com/competition/entrance/231670/introduction

**Comment by gathierry** [comment]
> @gathierry
> 
> It was excellent to see your code and results, thank you for sharing the training code.
> However, I couldn't find FashionAI dataset from their site, seems dataset is no more available. Could you please share trained model for inference. It will be very helpful for us to test it.
> 
> Best,
> Abhishek

Sorry I missed this message. The URL might have changed and you can find the competition with data here https://tianchi.aliyun.com/competition/entrance/231670/introduction.

I'm afraid I cannot share the trained model. I can't find it anymore on my machine. 😞
